name: 🪲 Bug Report
description: File a bug report
title: "[Bug Report] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? Please provide a detailed description of the issue.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I confirm that I have read and agree to abide by the Code of Conduct.
          required: true
