name: ⭐ Icon Request
description: Request a new icon
title: "[Icon Request] "
labels: ["icon request"]
body:
  - type: markdown
    attributes:
      value: |
        <br />
        We'd really appreciate it if you would consider starring our repository! It helps us gain visibility and support the project. ✨
        <br />
  - type: input
    id: icon-name
    attributes:
      label: Icon Name
      description: What's the icon name?
    validations:
      required: true
  - type: textarea
    id: icon-description
    attributes:
      label: Icon Description
      description: Why should we add this icon?
    validations:
      required: true
  - type: textarea
    id: reference-image
    attributes:
      label: Reference Image (Logo)
      description: Skill logo if available, please share it here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have searched for similar icon requests.
          required: true
        - label: I have checked if the icon is not already available.
          required: true
        - label: I confirm that I have read and agree to abide by the Code of Conduct.
          required: true